import pandas as pd


def get_candle_property(df: pd.DataFrame):

    """
    This function return some value which are generated by using change and close column.
    - pm => positive_mean : avarage of all positive candles change percent 
    - nm => negative_mean : avarage of all negative candles change percent
    - phm => positive_high_mean : avarage of all positive candles which are higher than pm value
    - p_count => positive_candle_count
    - n_count => negative_candle_count    
    @params
        - df : Dataframe
    @return
        - dict
    """


    # TODO #1 calculate how much candle does it take any sequential going up series (exp 3 sequential candle apx 1.5%)
    # TODO #1 So, we can easily calculate how much profit if you enter on this increase moment
    

    delta = df["change"]
    close = df["close"]

    change = (delta * 100) / (close - delta)

    p = change[change > 0]
    n = change[change < 0]

    return {
        "pm": p.mean(),
        "nm": n.mean(),
        "phm": p[p > p.mean()].mean(),
        "p_count": len(p),
        "n_count": len(n),
    }